[package]
name = "rustlib"
version = "0.1.0"

[dependencies]
rustr = "*"
rtsonlib = { git = "https://github.com/tercen/rtsonlib", tag = "0.2.3" }

[lib]
name = "rustlib"
crate-type = ["staticlib","rlib"]
